full_name: 'Acumulado de PLs apresentadas'
back_name: 'acumulado_pls_apresentadas'
variables:
      - column_name: 'tempo'
        data_title: 'tempo7'
        type: 'dropdown'
        options:
          multi: False
          clearable: False
          placeholder: False
          searchable: True
          value: None
      - column_name: 'tempo'
        data_title: 'tempo8'
        type: 'range_slider'
        options:
          allowcross: False
          dots: False
          count: 1
          included: False
          marks: None
          max: 10
          min: -5
          step: 0.5
          vertical: False
          value: [-3, 7]