full_name: 'Perfil das Tramitações'
back_name: 'perfil_tempo_tramitacao'
variables:
      - column_name: 'situacao_tipo'
        data_title: 'situacao-perfil'
        menu_text: 'tipo de situação (status)'
        type: 'dropdown'
        options:
          multi: True
          clearable: False
          placeholder: False
          searchable: True
          value: None
      - column_name: 'dataInicio'
        data_title: 'tempo-perfil'
        menu_text: 'intervalo de tempo'
        type: 'range_slider'
        options:
          aggregation: year
          allowcross: False
          dots: False
          count: 1
          included: True
          marks: None
          max: None
          min: None
          step: None
          vertical: False
          value: [-3, 7]