full_name: 'Número de PLs apresentadas'
back_name: 'numero_pls_apresentadas'
variables:
      - column_name: 'dataInicio'
        data_title: 'tempo-numero'
        menu_text: 'intervalo de tempo'
        type: 'range_slider'
        options:
          aggregation: year
          allowcross: False
          dots: False
          count: 1
          included: True
          marks: None
          max: 10
          min: -5
          step: 0.5
          vertical: False
          value: [-3, 7]